import type { ProvenanceRecordV1 } from "../contracts/provenanceContractV1";
import type { RightsEvidenceRecordV1 } from "../contracts/rightsEvidenceContractV1";
import type { SensoryQcRecordV1, TechnicalQcRecordV1 } from "../contracts/qcContractV1";

export const SLOW_RAIN_RECONCILED_EVIDENCE_VERSION_V1 = 1 as const;

export const SLOW_RAIN_EVIDENCE_REFERENCE_IDS_V1 = Object.freeze([
  "slow-rain-source-page-acquisition",
  "slow-rain-license-proof-acquisition",
  "slow-rain-provenance-reconciliation-r1",
  "slow-rain-mode-a-r4-decision",
  "slow-rain-mobile-physical-playback",
]);
const publicEvidenceReference = (id: string) => `soundscape-evidence-ref-v1:${id}`;

export const SLOW_RAIN_RECONCILED_EVIDENCE_V1 = Object.freeze({
  version: SLOW_RAIN_RECONCILED_EVIDENCE_VERSION_V1,
  catalogIdentity: "freesound-slow-rain-loop",
  soundscapeTitle: "Slow Rain",
  source: Object.freeze({
    provider: "Freesound",
    soundId: 177479,
    stableUri: "https://freesound.org/people/unfa/sounds/177479/",
    originalTitle: "Slowly Raining Loop",
    creator: "unfa",
    originalFilename: "177479__unfa__slowly-raining-loop.flac",
    expectedBytes: 5_068_413,
    checksumSha256: "fdc049ca0d7ebbcb2f0ea5c1130f47aac5814b5814bae93ae9e264bffa9fad82",
    mediaType: "audio/flac",
    durationSeconds: 73.415488,
    sampleRateHz: 44_100,
    channelCount: 2,
  }),
  catalogDerivative: Object.freeze({
    filename: "freesound-slow-rain-loop-v1.mp3",
    expectedBytes: 1_469_767,
    checksumSha256: "2bfd13bf7f3aecbbda80380d67a35901fe42bc0f4c77c76633088aa0d2f44d5b",
    mediaType: "audio/mpeg",
    durationSeconds: 73.456327,
    sampleRateHz: 44_100,
    channelCount: 2,
    bitrateKbps: 160,
  }),
  delivery: Object.freeze({
    filename: "freesound-slow-rain-loop__appsafe-v1.mp3",
    remoteUri: "https://soundscape.wellmadesystems.com/mobile-catalog-slice/kpfbNpr4n9exCDcz30C8Kp3Mzd8nNaHN/freesound-slow-rain-loop.mp3",
    expectedBytes: 1_763_181,
    checksumSha256: "47b22bf44964b2472df21850fb7b65d08e774edcb072887f755f5b28ba034d6a",
    mediaType: "audio/mpeg" as const,
    durationSeconds: 73.44,
    sampleRateHz: 48_000,
    channelCount: 2,
    bitrateKbps: 192,
    fullResponseStatus: 200,
    rangeResponseStatus: 206,
    hostedRouteAccepted: true,
  }),
  rights: Object.freeze({
    licenseName: "Creative Commons Zero v1.0 Universal",
    licenseShortName: "CC0 1.0",
    licenseVersion: "1.0",
    canonicalLicenseUri: "https://creativecommons.org/publicdomain/zero/1.0/",
    commercialUse: true,
    derivativeCreationAndDistribution: true,
    redistributionAndEmbedding: true,
    hostingAndStreaming: true,
    persistentOfflineCustomerDownload: true,
    attributionRequired: false,
    attributionText: null,
  }),
  qc: Object.freeze({
    sourceTechnicalQcAccepted: true,
    sourceToDeliveryByteChainAccepted: true,
    androidPhysicalPlaybackAccepted: true,
    iosPhysicalPlaybackAccepted: true,
    mobileListeningPlaybackAccepted: true,
    audiblyIdentifiedAsSlowRain: true,
    acceptedBy: "Daniel",
    acceptedOn: "2026-07-19",
    controllingDecision: "Exact app-safe Slow Rain bytes are accepted and must not be precluded from Alpha 0.14.0.",
  }),
});

const known = <T>(value: T, evidenceReferenceIds: readonly string[] = SLOW_RAIN_EVIDENCE_REFERENCE_IDS_V1) => Object.freeze({
  state: "known" as const,
  value,
  evidenceReferenceIds: Object.freeze([...evidenceReferenceIds]),
});
const notApplicable = (reason: string) => Object.freeze({ state: "not_applicable" as const, reason });
const measured = <T>(value: T, unit: string | null, method: string, limits: string) => Object.freeze({
  state: "measured" as const,
  value,
  unit,
  method,
  limits,
});
const notMeasured = (reason: string) => Object.freeze({ state: "not_measured" as const, reason });

export const createSlowRainReconciledProvenanceV1 = (): ProvenanceRecordV1 => Object.freeze({
  version: 1,
  catalogIdentity: SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity,
  sourceProviderIdentity: known(`freesound:${SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.soundId}`),
  canonicalSourceUrl: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.stableUri),
  originalTitle: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.originalTitle),
  creatorUploaderPublisher: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.creator),
  originalAssetIdentifier: known(String(SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.soundId)),
  acquisitionTimestamp: known("2026-06-11T05:56:00.825Z", ["slow-rain-source-page-acquisition"]),
  originalFilename: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.originalFilename),
  byteSize: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.expectedBytes),
  checksum: known(Object.freeze({ algorithm: "sha256" as const, value: SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.checksumSha256 })),
  mediaType: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.mediaType),
  originalAssetId: known(`freesound:${SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.soundId}:original-flac`),
  derivedAssetIds: Object.freeze([
    `${SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity}:catalog-mp3`,
    `${SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity}:appsafe-v1`,
  ]),
  relationships: Object.freeze([
    Object.freeze({ fromAssetId: `freesound:${SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.soundId}:original-flac`, toAssetId: `${SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity}:catalog-mp3`, relationship: "original_to_derived" as const }),
    Object.freeze({ fromAssetId: `${SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity}:catalog-mp3`, toAssetId: `${SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity}:appsafe-v1`, relationship: "original_to_derived" as const }),
    Object.freeze({ fromAssetId: SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity, toAssetId: `${SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity}:appsafe-v1`, relationship: "catalog_to_mobile_playback" as const }),
  ]),
  transformations: Object.freeze([
    Object.freeze({
      id: "slow-rain-source-flac-to-catalog-mp3",
      tool: known("FFmpeg"),
      toolVersion: known("6.1.1-3ubuntu5"),
      settings: known(Object.freeze({ codec: "libmp3lame", bitrateKbps: 160, sampleRateHz: 44_100, channels: 2 })),
      inputChecksum: known(Object.freeze({ algorithm: "sha256" as const, value: SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.checksumSha256 })),
      outputChecksum: known(Object.freeze({ algorithm: "sha256" as const, value: SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogDerivative.checksumSha256 })),
      timestamp: known("2026-07-19T13:26:35Z", ["slow-rain-provenance-reconciliation-r1"]),
      status: "completed" as const,
    }),
    Object.freeze({
      id: "slow-rain-catalog-mp3-to-appsafe-v1",
      tool: known("FFmpeg"),
      toolVersion: known("6.1.1-3ubuntu5"),
      settings: known(Object.freeze({ codec: "libmp3lame", bitrateKbps: 192, sampleRateHz: 48_000, channels: 2, metadata: "removed" })),
      inputChecksum: known(Object.freeze({ algorithm: "sha256" as const, value: SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogDerivative.checksumSha256 })),
      outputChecksum: known(Object.freeze({ algorithm: "sha256" as const, value: SLOW_RAIN_RECONCILED_EVIDENCE_V1.delivery.checksumSha256 })),
      timestamp: known("2026-07-19T13:26:35Z", ["slow-rain-provenance-reconciliation-r1"]),
      status: "completed" as const,
    }),
  ]),
  evidenceReferences: Object.freeze([
    Object.freeze({ id: "slow-rain-source-page-acquisition", kind: "snapshot" as const, locator: publicEvidenceReference("slow-rain-source-page-acquisition"), capturedAt: "2026-06-11T04:41:45.805Z" }),
    Object.freeze({ id: "slow-rain-license-proof-acquisition", kind: "file_record" as const, locator: publicEvidenceReference("slow-rain-license-proof-acquisition"), capturedAt: "2026-06-11T04:41:45.807Z" }),
    Object.freeze({ id: "slow-rain-provenance-reconciliation-r1", kind: "review_note" as const, locator: publicEvidenceReference("slow-rain-provenance-reconciliation-r1"), capturedAt: "2026-07-19T13:26:35Z" }),
    Object.freeze({ id: "slow-rain-mode-a-r4-decision", kind: "review_note" as const, locator: publicEvidenceReference("slow-rain-mode-a-r4-decision"), capturedAt: "2026-07-19" }),
    Object.freeze({ id: "slow-rain-mobile-physical-playback", kind: "review_note" as const, locator: publicEvidenceReference("slow-rain-mobile-physical-playback"), capturedAt: "2026-07-19" }),
  ]),
});

export const createSlowRainReconciledRightsV1 = (): RightsEvidenceRecordV1 => Object.freeze({
  version: 1,
  catalogIdentity: SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity,
  facts: Object.freeze({
    licenseName: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.rights.licenseName),
    licenseVersion: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.rights.licenseVersion),
    canonicalLicenseUrl: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.rights.canonicalLicenseUri),
    assertedBySource: known("Freesound source page for sound 177479 identifies Creative Commons 0."),
    capabilities: Object.freeze({
      commercialUse: known(true),
      derivatives: known(true),
      redistributionEmbedding: known(true),
      attributionRequired: known(false),
      shareAlikeOrNotice: known(false),
      providerSpecificTerms: known("CC0 standard caveats apply; no additional attribution or notice is required."),
    }),
    requiredAttributionText: notApplicable("CC0 1.0 requires no attribution."),
    requiredAttributionLinks: notApplicable("CC0 1.0 requires no attribution links."),
    sourceReference: known(SLOW_RAIN_RECONCILED_EVIDENCE_V1.source.stableUri),
    evidenceReferences: createSlowRainReconciledProvenanceV1().evidenceReferences,
  }),
  reviewDecision: Object.freeze({
    state: "approved_for_defined_use" as const,
    definedUse: known("Commercial Soundscape app playback, derivative distribution, hosted streaming, and persistent offline customer download of the exact app-safe delivery bytes."),
    reviewer: known("Daniel / Wellmade Systems", ["slow-rain-mode-a-r4-decision"]),
    reviewedAt: known("2026-07-19", ["slow-rain-mode-a-r4-decision"]),
    notes: known("Controlling r4 decision accepts the reconciled CC0 source-to-delivery identity and supersedes incomplete workflow-ledger states; this operational review is not a legal opinion."),
    sourceReference: known(publicEvidenceReference("slow-rain-provenance-reconciliation-r1")),
    legalOpinion: false as const,
  }),
});

export const createSlowRainReconciledTechnicalQcV1 = (): TechnicalQcRecordV1 => Object.freeze({
  version: 1,
  catalogIdentity: SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity,
  tool: known("FFmpeg/ffprobe plus exact HTTP full and Range byte verification"),
  toolVersion: known("FFmpeg 6.1.1-3ubuntu5"),
  measuredAt: known("2026-07-19T13:26:35Z"),
  measurements: Object.freeze({
    decodeReadability: measured(true, null, "ffprobe and full decode", "must decode without truncation"),
    containerCodec: measured("MP3", null, "ffprobe", "audio/mpeg delivery"),
    durationSeconds: measured(SLOW_RAIN_RECONCILED_EVIDENCE_V1.delivery.durationSeconds, "seconds", "ffprobe", "exact reconciled app-safe duration"),
    sampleRateHz: measured(SLOW_RAIN_RECONCILED_EVIDENCE_V1.delivery.sampleRateHz, "Hz", "ffprobe", "exact reconciled app-safe sample rate"),
    channelCount: measured(SLOW_RAIN_RECONCILED_EVIDENCE_V1.delivery.channelCount, "channels", "ffprobe", "stereo"),
    bitrateKbps: measured(SLOW_RAIN_RECONCILED_EVIDENCE_V1.delivery.bitrateKbps, "kbps", "ffprobe", "nominal app-safe bitrate"),
    byteSize: measured(SLOW_RAIN_RECONCILED_EVIDENCE_V1.delivery.expectedBytes, "bytes", "full HTTP response", "exact delivery byte count"),
    checksum: measured(SLOW_RAIN_RECONCILED_EVIDENCE_V1.delivery.checksumSha256, null, "SHA-256", "exact app-safe and hosted byte identity"),
    clippingPeakRisk: notMeasured("The accepted source QC records no clipping; an exact numeric peak is not asserted here."),
    loudnessLufs: notMeasured("No exact LUFS value is asserted by the reconciled evidence."),
    dcOffset: notMeasured("No exact DC-offset value is asserted by the reconciled evidence."),
    leadingSilenceSeconds: notMeasured("No exact leading-silence value is asserted by the reconciled evidence."),
    trailingSilenceSeconds: notMeasured("No exact trailing-silence value is asserted by the reconciled evidence."),
    sparseContent: notMeasured("The accepted source QC classifies this as a continuous background loop; no numeric sparsity value is asserted."),
    corruptionTruncation: measured(false, null, "full-byte download plus decode", "must not be corrupt or truncated"),
    fileSizeSanity: measured(true, null, "exact expected byte comparison", "must equal 1,763,181 bytes"),
    loopSeamClickRisk: measured("accepted restart-safe background loop", null, "accepted source QC and product loop policy", "no sudden level change or harsh seam evidence"),
    tailBehavior: measured("restart-safe", null, "accepted catalog loop policy", "bounded native restart behavior"),
    sourceSuitability: measured("approved exact source-to-delivery chain", null, "reconciled provenance and technical QC", "commercial app background-bed use"),
    mobilePlaybackSuitability: measured(true, null, "accepted Android and iOS physical playback", "exact hosted bytes audible on both platforms"),
  }),
  normalizationPolicy: "report_only_no_audio_change",
  loopReviewDecision: "approved",
  decision: "approved",
  decisionReason: "Exact app-safe bytes, media properties, source-to-delivery transforms, hosted full/Range responses, checksum, and cross-platform physical playback are accepted.",
});

export const createSlowRainReconciledSensoryQcV1 = (): SensoryQcRecordV1 => Object.freeze({
  version: 1,
  catalogIdentity: SLOW_RAIN_RECONCILED_EVIDENCE_V1.catalogIdentity,
  reviewer: known("Daniel", ["slow-rain-mode-a-r4-decision"]),
  reviewedAt: known("2026-07-19", ["slow-rain-mode-a-r4-decision"]),
  evidenceReferenceIds: Object.freeze(["slow-rain-mode-a-r4-decision", "slow-rain-mobile-physical-playback", "slow-rain-provenance-reconciliation-r1"]),
  audibility: known("Exact hosted bytes played audibly on physical Android and iOS and were identified as Slow Rain."),
  mixUsefulness: known("Accepted as the Rain Desk background bed and existing layered Slow Rain source."),
  maskingRisk: known("Accepted at bounded authored bed gain with native layer control."),
  sparseShortLivedBehavior: known("Continuous restart-safe rain background; not a sparse one-shot."),
  noise: known("Accepted rain texture; no disqualifying unexpected noise recorded."),
  artifacts: known("Daniel's controlling r4 decision accepts the exact app-safe derivative and supersedes the narrow incomplete listening-QC ledger state."),
  contentMismatch: known("No content mismatch; exact sound is Slow Rain."),
  namingTruth: known("Soundscape title Slow Rain truthfully maps to Slowly Raining Loop by unfa, Freesound sound 177479."),
  taxonomyTruth: known("Rain / light rain / environment background bed."),
  triggerMaterialActionFit: known("Steady rain is appropriate for Rain Desk's background trajectory."),
  sourceDescriptionMatch: known("The hosted app-safe delivery is deterministically derived from Freesound sound 177479."),
  loopSuitability: known("Accepted restart-safe background loop."),
  sensitivityExposureDecision: known("Non-voice, non-speech, default-safe rain background; no manual-only sensitivity gate required."),
  decision: "approved",
  reason: "Daniel accepted the exact established Slow Rain bytes for Alpha 0.14.0 after reconciled provenance, rights, delivery, and cross-platform playback evidence.",
});
