export type MobileVoiceMetadata = Readonly<{
  modality: "whisper" | "soft-spoken";
  synthetic: boolean;
  disclosureLabel: "Synthetic voice" | "Human voice";
  provenanceSummary: string;
  transcript: string;
}>;

export type MobileCatalogSound = {
  id: string;
  title: string;
  subtitle: string;
  audioUrl: string;
  category: string;
  lane: string;
  playable: boolean;
  containsVoice: boolean;
  voiceMetadata?: MobileVoiceMetadata;
  durationSeconds: number;
  clearLabelRequired: boolean;
  userChoiceOnly: boolean;
  loopEligible: boolean;
  layerMixGain?: number;
  tags: string[];
};

const MOBILE_CATALOG_AUDIO_BASE =
  "https://soundscape.wellmadesystems.com/mobile-catalog-slice/kpfbNpr4n9exCDcz30C8Kp3Mzd8nNaHN";

// Daniel-only internal mobile QA default catalog. This file keeps
// user-choice-only and hold-for-now sounds out of default Fast Start and Browse.
export const mobileCatalogSounds: MobileCatalogSound[] = [
  {
    id: "bulk5-005-long-rain-ambience",
    title: "Long Rain",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-005-long-rain-ambience.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 335.199,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "rain",
      "soft rain",
      "soft background",
      "steady background",
      "water",
      "Rain",
      "background_bed",
      "background",
    ],
  },
  {
    id: "freesound-slow-rain-loop",
    title: "Slow Rain",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/freesound-slow-rain-loop.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 73.415,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "rain",
      "soft rain",
      "soft background",
      "steady background",
      "water",
      "drips",
      "Rain",
      "background_bed",
      "background",
    ],
  },
  {
    id: "freesound-soft-rain-loop",
    title: "Soft Rain",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/freesound-soft-rain-loop.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 22.506,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "rain",
      "soft rain",
      "soft background",
      "steady background",
      "water",
      "drips",
      "Rain",
      "background_bed",
      "background",
    ],
  },
  {
    id: "pixabay-rainy-window-ambience",
    title: "Rainy Window",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/pixabay-rainy-window-ambience.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 119.688,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "rain",
      "soft rain",
      "soft background",
      "steady background",
      "rainy_window",
      "water",
      "drips",
      "Rain",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb10-040-gentle-river-flow",
    title: "Gentle River Flow",
    subtitle: "Flowing river water bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-040-gentle-river-flow.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 134.448,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "river",
      "water",
      "flowing water",
      "soft background",
      "steady background",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb10-041-small-flowing-creek-loop",
    title: "Small Flowing Creek",
    subtitle: "Flowing creek water bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-041-small-flowing-creek-loop.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 139.248,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "creek",
      "water",
      "flowing water",
      "soft background",
      "steady background",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb10-046-wyre-forest-stream",
    title: "Wyre Forest Stream",
    subtitle: "Water background texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-046-wyre-forest-stream.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 390.528,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "water",
      "stream",
      "flowing water",
      "soft background",
      "steady background",
      "background_noise",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb11-002-rain-on-tarp",
    title: "Rain on Tarp",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-002-rain-on-tarp.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 20.328,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "rain",
      "soft rain",
      "soft background",
      "steady background",
      "water",
      "Rain",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb11-004-munich-westpark-rain",
    title: "Munich Westpark Rain",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-004-munich-westpark-rain.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 87.648,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "rain",
      "soft rain",
      "soft background",
      "steady background",
      "water",
      "Rain",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-007-generated-soft-airflow-bed-a",
    title: "Soft Airflow A",
    subtitle: "Steady air and room tone",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-007-generated-soft-airflow-bed-a.mp3`,
    category: "fan-air-room",
    lane: "Fan / Air / Room",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "fan",
      "airflow",
      "room tone",
      "steady background",
      "steady",
      "steady_noise",
      "no_voice_soundscape",
      "background_noise",
      "Fan / Air / Room",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-008-generated-soft-airflow-bed-b",
    title: "Soft Airflow B",
    subtitle: "Steady air and room tone",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-008-generated-soft-airflow-bed-b.mp3`,
    category: "fan-air-room",
    lane: "Fan / Air / Room",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "fan",
      "airflow",
      "room tone",
      "steady background",
      "steady",
      "steady_noise",
      "no_voice_soundscape",
      "background_noise",
      "Fan / Air / Room",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-009-generated-low-room-hum-bed",
    title: "Low Room Hum",
    subtitle: "Steady air and room tone",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-009-generated-low-room-hum-bed.mp3`,
    category: "fan-air-room",
    lane: "Fan / Air / Room",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "fan",
      "airflow",
      "room tone",
      "steady background",
      "steady",
      "steady_noise",
      "no_voice_soundscape",
      "room_tone",
      "background_noise",
      "Fan / Air / Room",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-010-generated-soft-interior-air-bed",
    title: "Soft Interior Air",
    subtitle: "Steady air and room tone",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-010-generated-soft-interior-air-bed.mp3`,
    category: "fan-air-room",
    lane: "Fan / Air / Room",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "fan",
      "airflow",
      "room tone",
      "steady background",
      "steady",
      "steady_noise",
      "no_voice_soundscape",
      "room_tone",
      "background_noise",
      "Fan / Air / Room",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-022-small-stove-extractor-fan",
    title: "Small Stove Extractor Fan",
    subtitle: "Steady air and room tone",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-022-small-stove-extractor-fan.mp3`,
    category: "fan-air-room",
    lane: "Fan / Air / Room",
    playable: true,
    containsVoice: false,
    durationSeconds: 20.637,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fan",
      "airflow",
      "room tone",
      "steady background",
      "steady",
      "no_voice_soundscape",
      "background_noise",
      "Fan / Air / Room",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-023-stove-extractor-fan",
    title: "Stove Extractor Fan",
    subtitle: "Steady air and room tone",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-023-stove-extractor-fan.mp3`,
    category: "fan-air-room",
    lane: "Fan / Air / Room",
    playable: true,
    containsVoice: false,
    durationSeconds: 13.949,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fan",
      "airflow",
      "room tone",
      "steady background",
      "steady",
      "no_voice_soundscape",
      "background_noise",
      "Fan / Air / Room",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-024-refrigerator-hum",
    title: "Refrigerator Hum",
    subtitle: "Steady air and room tone",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-024-refrigerator-hum.mp3`,
    category: "fan-air-room",
    lane: "Fan / Air / Room",
    playable: true,
    containsVoice: false,
    durationSeconds: 35.892,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fan",
      "airflow",
      "room tone",
      "steady background",
      "steady",
      "no_voice_soundscape",
      "background_noise",
      "Fan / Air / Room",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-026-wind-blowing-ambience",
    title: "Wind Blowing",
    subtitle: "Steady air and room tone",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-026-wind-blowing-ambience.mp3`,
    category: "fan-air-room",
    lane: "Fan / Air / Room",
    playable: true,
    containsVoice: false,
    durationSeconds: 61.884,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fan",
      "airflow",
      "room tone",
      "steady background",
      "steady",
      "no_voice_soundscape",
      "background_noise",
      "Fan / Air / Room",
      "background_bed",
      "background",
    ],
  },
  {
    id: "brown-noise-soft-shell",
    title: "Brown Noise Soft Shell",
    subtitle: "Steady noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/brown-noise-soft-shell.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 60,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "brown noise",
      "steady noise",
      "soft background",
      "steady background",
      "brown_noise",
      "low_rumble",
      "steady_noise",
      "no_voice_soundscape",
      "Noise Colors",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-011-brown-noise-soft-low-bed-a",
    title: "Brown Noise Low A",
    subtitle: "Steady noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-011-brown-noise-soft-low-bed-a.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "brown noise",
      "steady noise",
      "soft background",
      "steady background",
      "steady_noise",
      "no_voice_soundscape",
      "brown_noise",
      "low_rumble",
      "Noise Colors",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-012-brown-noise-soft-low-bed-b",
    title: "Brown Noise Low B",
    subtitle: "Steady noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-012-brown-noise-soft-low-bed-b.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "brown noise",
      "steady noise",
      "soft background",
      "steady background",
      "steady_noise",
      "no_voice_soundscape",
      "brown_noise",
      "low_rumble",
      "Noise Colors",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-013-brown-noise-deep-low-bed",
    title: "Brown Noise Deep Low Bed",
    subtitle: "Steady noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-013-brown-noise-deep-low-bed.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "brown noise",
      "steady noise",
      "soft background",
      "steady background",
      "steady_noise",
      "no_voice_soundscape",
      "brown_noise",
      "low_rumble",
      "Noise Colors",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-014-pink-noise-smooth-bed-a",
    title: "Pink Noise Smooth A",
    subtitle: "Steady noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-014-pink-noise-smooth-bed-a.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "pink noise",
      "steady noise",
      "soft background",
      "steady background",
      "steady_noise",
      "no_voice_soundscape",
      "pink_noise",
      "Noise Colors",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-015-pink-noise-smooth-bed-b",
    title: "Pink Noise Smooth B",
    subtitle: "Steady noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-015-pink-noise-smooth-bed-b.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "pink noise",
      "steady noise",
      "soft background",
      "steady background",
      "steady_noise",
      "no_voice_soundscape",
      "pink_noise",
      "Noise Colors",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-016-pink-noise-gentle-wide-bed",
    title: "Pink Noise Gentle Wide Bed",
    subtitle: "Steady noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-016-pink-noise-gentle-wide-bed.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "pink noise",
      "steady noise",
      "soft background",
      "steady background",
      "steady_noise",
      "no_voice_soundscape",
      "pink_noise",
      "Noise Colors",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-017-white-noise-soft-bed-a",
    title: "White Noise Soft A",
    subtitle: "Steady noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-017-white-noise-soft-bed-a.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "white noise",
      "steady noise",
      "soft background",
      "steady background",
      "steady_noise",
      "no_voice_soundscape",
      "white_noise",
      "Noise Colors",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bulk5-004-water-flowing-in-the-river",
    title: "River Water Flow",
    subtitle: "Water background texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-004-water-flowing-in-the-river.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 180.147,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "water",
      "river",
      "stream",
      "water background",
      "soft background",
      "drips",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb8-175-elbe-riverside-night",
    title: "Riverside at Night",
    subtitle: "Water background texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-175-elbe-riverside-night.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 144.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "water",
      "river",
      "stream",
      "water background",
      "soft background",
      "real_room_ambience",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb8-177-small-river-trimmed",
    title: "Small River",
    subtitle: "Water background texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-177-small-river-trimmed.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 125.256,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "water",
      "river",
      "stream",
      "water background",
      "soft background",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb8-178-river-ambience",
    title: "River",
    subtitle: "Water background texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-178-river-ambience.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 214.128,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "water",
      "river",
      "stream",
      "water background",
      "soft background",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb8-179-icelandic-river-ambience",
    title: "Icelandic River",
    subtitle: "Water background texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-179-icelandic-river-ambience.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 356.448,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "water",
      "river",
      "stream",
      "water background",
      "soft background",
      "real_room_ambience",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-040-water-flowing-ambience-loop",
    title: "Water Flowing",
    subtitle: "Water background texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-040-water-flowing-ambience-loop.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 51.043,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: true,
    tags: [
      "water",
      "river",
      "stream",
      "water background",
      "soft background",
      "no_voice_soundscape",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-041-river-water-flowing",
    title: "River Water Flowing",
    subtitle: "Water background texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-041-river-water-flowing.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 180.193,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "water",
      "river",
      "stream",
      "water background",
      "soft background",
      "no_voice_soundscape",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "rbb-042-waterfall-ambience",
    title: "Waterfall",
    subtitle: "Water background texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-042-waterfall-ambience.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 13.296,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "water",
      "river",
      "stream",
      "water background",
      "soft background",
      "no_voice_soundscape",
      "Water",
      "background_bed",
      "background",
    ],
  },
  {
    id: "bb10-001-window-tapping-three-types",
    title: "Window Tapping Three Types",
    subtitle: "Nature background ambience",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-001-window-tapping-three-types.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 23.856,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "window tapping",
      "soft tapping",
      "nature accent",
      "glass",
      "tapping",
      "sharp_tapping",
      "repetition",
      "Forest / Nature / Wind",
      "background_bed",
      "accent",
    ],
  },
  {
    id: "bb10-042-jungle-frogs-and-crickets",
    title: "Jungle Frogs & Crickets",
    subtitle: "Nature background ambience",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-042-jungle-frogs-and-crickets.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 46.032,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "nature",
      "forest",
      "crickets",
      "night ambience",
      "background",
      "background_noise",
      "Forest / Nature / Wind",
      "background_bed",
    ],
  },
  {
    id: "bb11-013-frogs-crickets-night",
    title: "Frogs & Crickets Night",
    subtitle: "Nature background ambience",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-013-frogs-crickets-night.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 86.76,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "nature",
      "forest",
      "crickets",
      "night ambience",
      "background",
      "background_noise",
      "Forest / Nature / Wind",
      "background_bed",
    ],
  },
  {
    id: "bulk6-003-european-forest-ambience",
    title: "European Forest",
    subtitle: "Nature background ambience",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk6-003-european-forest-ambience.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 161.328,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "nature",
      "forest",
      "wind",
      "night ambience",
      "background",
      "real_room_ambience",
      "background_noise",
      "Forest / Nature / Wind",
      "background_bed",
    ],
  },
  {
    id: "bulk6-005-pond-crickets-ambience",
    title: "Pond Crickets",
    subtitle: "Nature background ambience",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk6-005-pond-crickets-ambience.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 148.104,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "nature",
      "forest",
      "crickets",
      "night ambience",
      "background",
      "water",
      "real_room_ambience",
      "Forest / Nature / Wind",
      "background_bed",
    ],
  },
  {
    id: "bulk6-008-summer-forest-night",
    title: "Summer Forest Night",
    subtitle: "Nature background ambience",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk6-008-summer-forest-night.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 126.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "nature",
      "forest",
      "wind",
      "night ambience",
      "background",
      "real_room_ambience",
      "background_noise",
      "Forest / Nature / Wind",
      "background_bed",
    ],
  },
  {
    id: "bulk6-010-forest-frogs-ambience",
    title: "Forest Frogs",
    subtitle: "Nature background ambience",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk6-010-forest-frogs-ambience.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 113.856,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "nature",
      "forest",
      "crickets",
      "night ambience",
      "background",
      "water",
      "real_room_ambience",
      "background_noise",
      "Forest / Nature / Wind",
      "background_bed",
    ],
  },
  {
    id: "bulk6-016-night-crickets",
    title: "Night Crickets",
    subtitle: "Nature background ambience",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk6-016-night-crickets.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 90.168,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "nature",
      "forest",
      "crickets",
      "night ambience",
      "background",
      "real_room_ambience",
      "Forest / Nature / Wind",
      "background_bed",
    ],
  },
  {
    id: "rbb-047-night-forest-with-insects",
    title: "Night Forest with Insects",
    subtitle: "Nature background ambience",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-047-night-forest-with-insects.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 84.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "nature",
      "forest",
      "crickets",
      "night ambience",
      "background",
      "no_voice_soundscape",
      "background_noise",
      "Forest / Nature / Wind",
      "background_bed",
    ],
  },
  {
    id: "bulk5-003-phone-keyboard-bit",
    title: "Phone Keyboard Taps",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-003-phone-keyboard-bit.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 8.399,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "typing",
      "keyboard taps",
      "desk texture",
      "tapping",
      "object_tapping",
      "buttons",
      "Writing / Typing",
      "accent_or_texture",
      "texture",
    ],
  },
  {
    id: "bb10-013-pencil-writing-two",
    title: "Pencil Writing Two",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-013-pencil-writing-two.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 16.248,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "writing",
      "pencil",
      "paper texture",
      "desk texture",
      "paper",
      "Writing / Typing",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bb10-014-thick-paper-pencil-writing",
    title: "Thick Paper Pencil Writing",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-014-thick-paper-pencil-writing.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 14.976,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "writing",
      "pencil",
      "paper texture",
      "desk texture",
      "paper",
      "Writing / Typing",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bb10-015-writing-pen",
    title: "Writing Pen",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-015-writing-pen.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.768,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "writing",
      "pen",
      "paper texture",
      "desk texture",
      "paper",
      "Writing / Typing",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bb10-016-pen-writing-on-paper",
    title: "Pen Writing on Paper",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-016-pen-writing-on-paper.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 17.52,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "writing",
      "pen",
      "paper texture",
      "desk texture",
      "paper",
      "Writing / Typing",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bb10-019-notebook-writing",
    title: "Notebook Writing",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-019-notebook-writing.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 83.28,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "writing",
      "pen",
      "paper texture",
      "desk texture",
      "paper",
      "Writing / Typing",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bb11-003-very-slow-typing",
    title: "Very Slow Typing",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-003-very-slow-typing.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 21.72,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "typing",
      "keyboard taps",
      "desk texture",
      "writing",
      "Writing / Typing",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "asmr50-051-cardboard-box-tapping-asmr",
    title: "Cardboard Box Tapping",
    subtitle: "Paper and page texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/asmr50-051-cardboard-box-tapping-asmr.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 423.768,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper tapping",
      "object tapping",
      "accent texture",
      "tapping",
      "object_tapping",
      "repetition",
      "Paper / Pages",
      "background_bed",
      "accent",
    ],
  },
  {
    id: "bulk5-010-box-tapping-contact-mic",
    title: "Box Tapping",
    subtitle: "Paper and page texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-010-box-tapping-contact-mic.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 32.207,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper tapping",
      "object tapping",
      "accent texture",
      "tapping",
      "object_tapping",
      "sharp_tapping",
      "Paper / Pages",
      "background_bed",
      "accent",
    ],
  },
  {
    id: "bb10-011-quick-book-page-turning",
    title: "Quick Book Page Turning",
    subtitle: "Paper and page texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-011-quick-book-page-turning.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 17.28,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper",
      "pages",
      "page turning",
      "soft texture",
      "rustle",
      "Paper / Pages",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bulk6-108-fingernail-tapping",
    title: "Fingernail Tapping",
    subtitle: "Paper and page texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk6-108-fingernail-tapping.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 109.032,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper tapping",
      "object tapping",
      "accent texture",
      "tapping",
      "object_tapping",
      "sharp_tapping",
      "Paper / Pages",
      "background_bed",
      "accent",
    ],
  },
  {
    id: "asmr50-016-hair-brushing-sfx",
    title: "Hair Brushing",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/asmr50-016-hair-brushing-sfx.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 138.325,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    layerMixGain: 3.2,
    tags: [
      "fabric",
      "cloth rustle",
      "soft texture",
      "tactile",
      "brush",
      "rustle",
      "Fabric / Soft Texture",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bulk3-016-fabric-rustling",
    title: "Fabric Rustling",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk3-016-fabric-rustling.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 50,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fabric",
      "cloth rustle",
      "soft texture",
      "tactile",
      "rustle",
      "busy_texture",
      "Fabric / Soft Texture",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bulk4-018-rough-fabric-rustle",
    title: "Rough Fabric Rustle",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk4-018-rough-fabric-rustle.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 103.416,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fabric",
      "cloth rustle",
      "soft texture",
      "tactile",
      "rustle",
      "Fabric / Soft Texture",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bulk4-019-zipper-hoodie-clothes-rustle",
    title: "Zipper & Hoodie Clothes Rustle",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk4-019-zipper-hoodie-clothes-rustle.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 97.042,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fabric",
      "cloth rustle",
      "soft texture",
      "tactile",
      "rustle",
      "Fabric / Soft Texture",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "bulk4-020-cloth-rustle-8",
    title: "Cloth Rustle 8",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk4-020-cloth-rustle-8.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 93.766,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fabric",
      "cloth rustle",
      "soft texture",
      "tactile",
      "rustle",
      "Fabric / Soft Texture",
      "background_bed",
      "texture",
    ],
  },
  {
    id: "asmr50-002-ribbon-box-tapping-asmr",
    title: "Ribbon Box Tapping",
    subtitle: "Object-tapping accent",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/asmr50-002-ribbon-box-tapping-asmr.mp3`,
    category: "tapping-object-foley",
    lane: "Tapping / Object Foley",
    playable: true,
    containsVoice: false,
    durationSeconds: 602.736,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "tapping",
      "object foley",
      "accent texture",
      "object_tapping",
      "repetition",
      "Tapping / Object Foley",
      "background_bed",
      "accent",
    ],
  },
  {
    id: "asmr50-052-plastic-container-tapping-asmr",
    title: "Plastic Container Tapping",
    subtitle: "Object-tapping accent",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/asmr50-052-plastic-container-tapping-asmr.mp3`,
    category: "tapping-object-foley",
    lane: "Tapping / Object Foley",
    playable: true,
    containsVoice: false,
    durationSeconds: 602.136,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "tapping",
      "object foley",
      "accent texture",
      "plastic",
      "object_tapping",
      "repetition",
      "Tapping / Object Foley",
      "background_bed",
      "accent",
    ],
  },
  {
    id: "bb9-086-gentle-spring-rain",
    title: "Gentle Spring Rain",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb9-086-gentle-spring-rain.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 476.352,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "bb9-095-steady-city-rain",
    title: "Steady City Rain",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb9-095-steady-city-rain.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 185.712,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "bb9-096-indoor-window-rain",
    title: "Indoor Window Rain",
    subtitle: "Window rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb9-096-indoor-window-rain.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 457.344,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "bb9-093-steady-night-rain",
    title: "Steady Night Rain",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb9-093-steady-night-rain.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 210.552,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "bb9-088-heavy-porch-rain",
    title: "Heavy Porch Rain",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb9-088-heavy-porch-rain.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 306.264,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "bb11-008-continuous-rain-atmosphere",
    title: "Continuous Rain Atmosphere",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-008-continuous-rain-atmosphere.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 80.232,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "rbb-030-light-rain-loop",
    title: "Light Rain Loop",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-030-light-rain-loop.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 15.047,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "rbb-031-light-rain-loop-variant",
    title: "Light Rain Loop Variant",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-031-light-rain-loop-variant.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 39.419,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "rbb-032-rain-long-loop",
    title: "Rain Long Loop",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-032-rain-long-loop.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 57.104,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "rbb-033-forest-rain-loop",
    title: "Forest Rain Loop",
    subtitle: "Rain background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-033-forest-rain-loop.mp3`,
    category: "rain",
    lane: "Rain",
    playable: true,
    containsVoice: false,
    durationSeconds: 24.79,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Rain",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "rain",
      "rain bed",
      "rain_bed",
      "sleep_safe",
      "soft rain",
      "stable background",
      "stable_bed",
      "water",
    ],
  },
  {
    id: "bb11-006-soft-creek-detail",
    title: "Soft Creek Detail",
    subtitle: "Creek and stream water bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-006-soft-creek-detail.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 59.376,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Water",
      "background",
      "background_bed",
      "builder_foundation",
      "flowing water",
      "focus_safe",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "water",
      "water bed",
      "water_bed",
    ],
  },
  {
    id: "bb11-015-small-forest-stream",
    title: "Small Forest Stream",
    subtitle: "Creek and stream water bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-015-small-forest-stream.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 71.352,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Water",
      "background",
      "background_bed",
      "builder_foundation",
      "flowing water",
      "focus_safe",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "water",
      "water bed",
      "water_bed",
    ],
  },
  {
    id: "bb11-016-large-brook-stream",
    title: "Large Brook Stream",
    subtitle: "Creek and stream water bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-016-large-brook-stream.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 65.064,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Water",
      "background",
      "background_bed",
      "builder_foundation",
      "flowing water",
      "focus_safe",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "water",
      "water bed",
      "water_bed",
    ],
  },
  {
    id: "bb11-017-medium-stream-water",
    title: "Medium Stream Water",
    subtitle: "Creek and stream water bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-017-medium-stream-water.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 61.152,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Water",
      "background",
      "background_bed",
      "builder_foundation",
      "flowing water",
      "focus_safe",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "water",
      "water bed",
      "water_bed",
    ],
  },
  {
    id: "bb11-018-creek-moderate-flow",
    title: "Creek Moderate Flow",
    subtitle: "Creek and stream water bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-018-creek-moderate-flow.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 60.576,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Water",
      "background",
      "background_bed",
      "builder_foundation",
      "flowing water",
      "focus_safe",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "water",
      "water bed",
      "water_bed",
    ],
  },
  {
    id: "bb11-022-creek-water-stream",
    title: "Creek Water Stream",
    subtitle: "Creek and stream water bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-022-creek-water-stream.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 36.672,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Water",
      "background",
      "background_bed",
      "builder_foundation",
      "flowing water",
      "focus_safe",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "water",
      "water bed",
      "water_bed",
    ],
  },
  {
    id: "rbb-044-sea-waves-ambience",
    title: "Sea Waves Ambience",
    subtitle: "Sea water background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-044-sea-waves-ambience.mp3`,
    category: "water",
    lane: "Water",
    playable: true,
    containsVoice: false,
    durationSeconds: 151.719,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Water",
      "background",
      "background_bed",
      "builder_foundation",
      "flowing water",
      "focus_safe",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "water",
      "water bed",
      "water_bed",
    ],
  },
  {
    id: "rbb-018-white-noise-soft-bed-b",
    title: "White Noise Soft Bed B",
    subtitle: "Soft white noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-018-white-noise-soft-bed-b.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Noise Colors",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "noise_bed",
      "noise_sensitive",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "steady noise",
    ],
  },
  {
    id: "rbb-019-filtered-white-noise-soft-airlike-bed",
    title: "Filtered White Noise Soft Airlike Bed",
    subtitle: "Soft white noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-019-filtered-white-noise-soft-airlike-bed.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Noise Colors",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "noise_bed",
      "noise_sensitive",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "steady noise",
    ],
  },
  {
    id: "rbb-020-brown-noise-warm-bed-c",
    title: "Brown Noise Warm Bed C",
    subtitle: "Warm brown noise background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-020-brown-noise-warm-bed-c.mp3`,
    category: "noise-colors",
    lane: "Noise Colors",
    playable: true,
    containsVoice: false,
    durationSeconds: 30.024,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Noise Colors",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "noise_bed",
      "noise_sensitive",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "steady noise",
    ],
  },
  {
    id: "rbb-075-european-spring-forest-ambience",
    title: "European Spring Forest Ambience",
    subtitle: "Forest nature background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-075-european-spring-forest-ambience.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 115.968,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "forest",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
    ],
  },
  {
    id: "rbb-076-quiet-forest-ambience",
    title: "Quiet Forest Ambience",
    subtitle: "Forest nature background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-076-quiet-forest-ambience.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 152.112,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "forest",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
    ],
  },
  {
    id: "rbb-077-spring-forest-with-woodpeckers",
    title: "Spring Forest with Woodpeckers",
    subtitle: "Forest nature background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-077-spring-forest-with-woodpeckers.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 110.04,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "birds",
      "builder_foundation",
      "focus_safe",
      "forest",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
    ],
  },
  {
    id: "rbb-085-breeze-through-the-trees",
    title: "Breeze Through the Trees",
    subtitle: "Wind and trees background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-085-breeze-through-the-trees.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 14.376,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
      "wind_bed",
    ],
  },
  {
    id: "rbb-090-light-wind",
    title: "Light Wind",
    subtitle: "Wind and trees background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-090-light-wind.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 18.072,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
      "wind_bed",
    ],
  },
  {
    id: "rbb-091-meadow-wind-light",
    title: "Meadow Wind Light",
    subtitle: "Wind and trees background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-091-meadow-wind-light.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 23.808,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
      "wind_bed",
    ],
  },
  {
    id: "rbb-097-wind-in-the-forest",
    title: "Wind in the Forest",
    subtitle: "Wind and trees background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-097-wind-in-the-forest.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 25.368,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "forest",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
      "wind_bed",
    ],
  },
  {
    id: "rbb-098-wind-in-the-forest-loop",
    title: "Wind in the Forest Loop",
    subtitle: "Wind and trees background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-098-wind-in-the-forest-loop.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 12.576,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "forest",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
      "wind_bed",
    ],
  },
  {
    id: "rbb-084-arctic-winds",
    title: "Arctic Winds",
    subtitle: "Wind and trees background bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-084-arctic-winds.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 38.976,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "focus_safe",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
      "wind_bed",
    ],
  },
  {
    id: "rbb-078-summer-crickets-loop",
    title: "Summer Crickets Loop",
    subtitle: "Night crickets nature bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-078-summer-crickets-loop.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 18.864,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "crickets",
      "focus_safe",
      "insects",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
    ],
  },
  {
    id: "rbb-079-summer-night-crickets",
    title: "Summer Night Crickets",
    subtitle: "Night crickets nature bed",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/rbb-079-summer-night-crickets.mp3`,
    category: "forest-nature-wind",
    lane: "Forest / Nature / Wind",
    playable: true,
    containsVoice: false,
    durationSeconds: 32.736,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "Forest / Nature / Wind",
      "background",
      "background_bed",
      "builder_foundation",
      "crickets",
      "focus_safe",
      "insects",
      "nature",
      "nature bed",
      "nature_bed",
      "sleep_safe",
      "stable background",
      "stable_bed",
      "wind",
    ],
  },
  {
    id: "bb11-040-ball-pen-writing",
    title: "Ball Pen Writing",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-040-ball-pen-writing.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 64.104,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "typing",
      "writing",
      "Writing / Typing",
      "texture",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "writing_texture",
    ],
  },
  {
    id: "bb11-046-pencil-on-paper",
    title: "Pencil on Paper",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-046-pencil-on-paper.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 36.336,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "typing",
      "writing",
      "Writing / Typing",
      "texture",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "writing_texture",
    ],
  },
  {
    id: "bb11-051-pen-writing-on-paper",
    title: "Pen Writing on Paper",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-051-pen-writing-on-paper.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 28.224,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "typing",
      "writing",
      "Writing / Typing",
      "texture",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "writing_texture",
    ],
  },
  {
    id: "bb11-052-writing",
    title: "Writing",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-052-writing.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 26.136,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "typing",
      "writing",
      "Writing / Typing",
      "texture",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "writing_texture",
    ],
  },
  {
    id: "bb11-043-marker-on-whiteboard",
    title: "Marker on Whiteboard",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-043-marker-on-whiteboard.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 59.424,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "typing",
      "writing",
      "Writing / Typing",
      "texture",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "writing_texture",
    ],
  },
  {
    id: "bb11-032-slow-typing",
    title: "Slow Typing",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-032-slow-typing.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 49.824,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "typing",
      "writing",
      "Writing / Typing",
      "texture",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "writing_texture",
    ],
  },
  {
    id: "bb11-012-notebook-writing-pages",
    title: "Notebook Writing Pages",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-012-notebook-writing-pages.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 72.696,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "typing",
      "writing",
      "Writing / Typing",
      "texture",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "writing_texture",
    ],
  },
  {
    id: "bb11-054-marker-on-paper",
    title: "Marker on Paper",
    subtitle: "Writing and typing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb11-054-marker-on-paper.mp3`,
    category: "writing-typing",
    lane: "Writing / Typing",
    playable: true,
    containsVoice: false,
    durationSeconds: 21.504,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "typing",
      "writing",
      "Writing / Typing",
      "texture",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "writing_texture",
    ],
  },
  {
    id: "asmr50-017-coat-brushing-texture",
    title: "Coat Brushing Texture",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/asmr50-017-coat-brushing-texture.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 17.496,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fabric",
      "foreground",
      "rustle",
      "Fabric / Soft Texture",
      "texture",
      "asmr_texture",
      "builder_texture",
      "fabric_texture",
      "focus_safe",
      "low_volume_layer",
    ],
  },
  {
    id: "bulk3-014-soft-fabric-rustle",
    title: "Soft Fabric Rustle",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk3-014-soft-fabric-rustle.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 12.504,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    layerMixGain: 4,
    tags: [
      "fabric",
      "foreground",
      "rustle",
      "Fabric / Soft Texture",
      "texture",
      "asmr_texture",
      "builder_texture",
      "fabric_texture",
      "focus_safe",
      "low_volume_layer",
    ],
  },
  {
    id: "bulk4-023-fabric-texture-062710",
    title: "Soft Fabric Texture",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk4-023-fabric-texture-062710.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 74.592,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fabric",
      "foreground",
      "rustle",
      "Fabric / Soft Texture",
      "texture",
      "asmr_texture",
      "builder_texture",
      "fabric_texture",
      "focus_safe",
      "low_volume_layer",
    ],
  },
  {
    id: "bulk5-017-fabric-touched-by-hand",
    title: "Fabric Touched by Hand",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-017-fabric-touched-by-hand.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 40.152,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fabric",
      "foreground",
      "rustle",
      "Fabric / Soft Texture",
      "texture",
      "asmr_texture",
      "builder_texture",
      "fabric_texture",
      "focus_safe",
      "low_volume_layer",
    ],
  },
  {
    id: "bb7-050-cloth-rustle",
    title: "Cloth Rustle",
    subtitle: "Soft tactile texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb7-050-cloth-rustle.mp3`,
    category: "fabric-soft-texture",
    lane: "Fabric / Soft Texture",
    playable: true,
    containsVoice: false,
    durationSeconds: 25.8,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "fabric",
      "foreground",
      "rustle",
      "Fabric / Soft Texture",
      "texture",
      "asmr_texture",
      "builder_texture",
      "fabric_texture",
      "focus_safe",
      "low_volume_layer",
    ],
  },
  {
    id: "bulk3-019-soft-door-knock",
    title: "Soft Door Knock",
    subtitle: "Object-tapping accent",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk3-019-soft-door-knock.mp3`,
    category: "tapping-object-foley",
    lane: "Tapping / Object Foley",
    playable: true,
    containsVoice: false,
    durationSeconds: 9.84,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "object",
      "tapping",
      "Tapping / Object Foley",
      "accent",
      "interaction_foley",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "object_accent",
    ],
  },
  {
    id: "bulk5-008-wood-tap",
    title: "Wood Tap",
    subtitle: "Object-tapping accent",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-008-wood-tap.mp3`,
    category: "tapping-object-foley",
    lane: "Tapping / Object Foley",
    playable: true,
    containsVoice: false,
    durationSeconds: 60.048,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "object",
      "sharp",
      "tapping",
      "Tapping / Object Foley",
      "accent",
      "interaction_foley",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "object_accent",
    ],
  },
  {
    id: "bb8-074-soft-object-tapping",
    title: "Soft Object Tapping",
    subtitle: "Object-tapping accent",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-074-soft-object-tapping.mp3`,
    category: "tapping-object-foley",
    lane: "Tapping / Object Foley",
    playable: true,
    containsVoice: false,
    durationSeconds: 82.848,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "object",
      "sharp",
      "tapping",
      "Tapping / Object Foley",
      "accent",
      "interaction_foley",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "object_accent",
    ],
  },
  {
    id: "bulk5-022-rimel-texture",
    title: "Small Brush Texture",
    subtitle: "Object-tapping accent",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-022-rimel-texture.mp3`,
    category: "tapping-object-foley",
    lane: "Tapping / Object Foley",
    playable: true,
    containsVoice: false,
    durationSeconds: 31.944,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "foreground",
      "object",
      "tapping",
      "Tapping / Object Foley",
      "accent",
      "interaction_foley",
      "asmr_texture",
      "builder_texture",
      "focus_safe",
      "low_volume_layer",
      "object_accent",
    ],
  },
  {
    id: "bulk3-012-sketchbook-page-flips",
    title: "Sketchbook Page Flips",
    subtitle: "Gentle page-turning texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk3-012-sketchbook-page-flips.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 8.108,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper",
      "pages",
      "page turn",
      "paper texture",
      "Paper / Pages",
      "texture",
      "asmr_texture",
      "builder_texture",
      "low_volume_layer",
      "not_default_fast_start",
    ],
  },
  {
    id: "bulk4-029-page-turning-1",
    title: "Page Turning 1",
    subtitle: "Gentle page-turning texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk4-029-page-turning-1.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 26.686,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper",
      "pages",
      "page turn",
      "paper texture",
      "Paper / Pages",
      "texture",
      "asmr_texture",
      "builder_texture",
      "low_volume_layer",
      "not_default_fast_start",
    ],
  },
  {
    id: "bulk5-001-fast-browsing-book-paging",
    title: "Fast Browsing Book Paging",
    subtitle: "Fast page-browsing texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-001-fast-browsing-book-paging.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 9.28,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper",
      "pages",
      "page turn",
      "paper texture",
      "Paper / Pages",
      "texture",
      "asmr_texture",
      "builder_texture",
      "low_volume_layer",
      "not_default_fast_start",
      "foreground",
      "busy",
    ],
  },
  {
    id: "bulk5-002-turning-newspaper-big-page",
    title: "Turning Newspaper Big Page",
    subtitle: "Newspaper page-turning texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-002-turning-newspaper-big-page.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 9.41,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper",
      "pages",
      "page turn",
      "paper texture",
      "Paper / Pages",
      "texture",
      "asmr_texture",
      "builder_texture",
      "low_volume_layer",
      "not_default_fast_start",
      "foreground",
      "busy",
    ],
  },
  {
    id: "bulk5-027-book-turning-pages-02",
    title: "Book Turning Pages 02",
    subtitle: "Gentle page-turning texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-027-book-turning-pages-02.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 22.808,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper",
      "pages",
      "page turn",
      "paper texture",
      "Paper / Pages",
      "texture",
      "asmr_texture",
      "builder_texture",
      "low_volume_layer",
      "not_default_fast_start",
    ],
  },
  {
    id: "bulk5-024-turning-pages-in-book",
    title: "Turning Pages in Book",
    subtitle: "Gentle page-turning texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk5-024-turning-pages-in-book.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 101,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    layerMixGain: 1.5,
    tags: [
      "paper",
      "pages",
      "page turn",
      "paper texture",
      "Paper / Pages",
      "texture",
      "asmr_texture",
      "builder_texture",
      "low_volume_layer",
      "not_default_fast_start",
    ],
  },
  {
    id: "bulk6-107-book-page-turning",
    title: "Book Page Turning",
    subtitle: "Gentle page-turning texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bulk6-107-book-page-turning.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 9.408,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper",
      "pages",
      "page turn",
      "paper texture",
      "Paper / Pages",
      "texture",
      "asmr_texture",
      "builder_texture",
      "low_volume_layer",
      "not_default_fast_start",
    ],
  },
  {
    id: "bb7-035-gentle-turning-pages",
    title: "Gentle Turning Pages",
    subtitle: "Gentle page-turning texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb7-035-gentle-turning-pages.mp3`,
    category: "paper-pages",
    lane: "Paper / Pages",
    playable: true,
    containsVoice: false,
    durationSeconds: 45.312,
    clearLabelRequired: false,
    userChoiceOnly: false,
    loopEligible: false,
    tags: [
      "paper",
      "pages",
      "page turn",
      "paper texture",
      "Paper / Pages",
      "texture",
      "asmr_texture",
      "builder_texture",
      "low_volume_layer",
      "not_default_fast_start",
    ],
  },

  {
    id: "bb8-049-high-quiet-singing-bowl",
    title: "High Quiet Singing Bowl",
    subtitle: "Clear-labeled singing bowl texture",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-049-high-quiet-singing-bowl.mp3`,
    category: "tones-resonance",
    lane: "Tones / Resonance",
    playable: true,
    containsVoice: false,
    durationSeconds: 19.128,
    clearLabelRequired: true,
    userChoiceOnly: true,
    loopEligible: false,
    tags: [
      "singing bowl",
      "bowl",
      "resonance",
      "tones",
      "tone",
      "resonant",
      "chime texture",
      "Tones / Resonance",
      "accent",
      "bowl_texture",
      "opt_in_texture",
      "low_volume_layer",
      "user_choice_only",
      "not_default_fast_start",
    ],
  },
  {
    id: "bb8-047-singing-bowl-hit-1",
    title: "Singing Bowl Hit 1",
    subtitle: "Clear-labeled singing bowl accent",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-047-singing-bowl-hit-1.mp3`,
    category: "tones-resonance",
    lane: "Tones / Resonance",
    playable: true,
    containsVoice: false,
    durationSeconds: 16.584,
    clearLabelRequired: true,
    userChoiceOnly: true,
    loopEligible: false,
    tags: [
      "singing bowl",
      "bowl",
      "resonance",
      "tones",
      "tone",
      "resonant",
      "chime texture",
      "Tones / Resonance",
      "accent",
      "bowl_texture",
      "opt_in_texture",
      "low_volume_layer",
      "user_choice_only",
      "not_default_fast_start",
    ],
  },
  {
    id: "bb8-052-singing-bowl-hit-2",
    title: "Singing Bowl Hit 2",
    subtitle: "Clear-labeled singing bowl accent",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-052-singing-bowl-hit-2.mp3`,
    category: "tones-resonance",
    lane: "Tones / Resonance",
    playable: true,
    containsVoice: false,
    durationSeconds: 16.392,
    clearLabelRequired: true,
    userChoiceOnly: true,
    loopEligible: false,
    tags: [
      "singing bowl",
      "bowl",
      "resonance",
      "tones",
      "tone",
      "resonant",
      "chime texture",
      "Tones / Resonance",
      "accent",
      "bowl_texture",
      "opt_in_texture",
      "low_volume_layer",
      "user_choice_only",
      "not_default_fast_start",
    ],
  },
  {
    id: "bb8-012-singing-bowl-low-resonance",
    title: "Singing Bowl Low Resonance",
    subtitle: "Clear-labeled low bowl resonance",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-012-singing-bowl-low-resonance.mp3`,
    category: "tones-resonance",
    lane: "Tones / Resonance",
    playable: true,
    containsVoice: false,
    durationSeconds: 14.952,
    clearLabelRequired: true,
    userChoiceOnly: true,
    loopEligible: false,
    tags: [
      "singing bowl",
      "bowl",
      "resonance",
      "tones",
      "tone",
      "resonant",
      "drone",
      "Tones / Resonance",
      "background",
      "tone_bed",
      "opt_in_background",
      "low_volume_layer",
      "user_choice_only",
      "not_default_fast_start",
    ],
  },
  {
    id: "bb8-041-singing-bowls-ensemble",
    title: "Singing Bowls Ensemble",
    subtitle: "Clear-labeled bowl resonance background",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb8-041-singing-bowls-ensemble.mp3`,
    category: "tones-resonance",
    lane: "Tones / Resonance",
    playable: true,
    containsVoice: false,
    durationSeconds: 168.408,
    clearLabelRequired: true,
    userChoiceOnly: true,
    loopEligible: false,
    tags: [
      "singing bowls",
      "bowl",
      "resonance",
      "tones",
      "tone",
      "resonant",
      "drone",
      "Tones / Resonance",
      "background",
      "tone_bed",
      "opt_in_background",
      "low_volume_layer",
      "user_choice_only",
      "not_default_fast_start",
    ],
  },
  {
    id: "bb10-051-japanese-temple-singing-bowl",
    title: "Japanese Temple Singing Bowl",
    subtitle: "Clear-labeled singing bowl resonance",
    audioUrl: `${MOBILE_CATALOG_AUDIO_BASE}/bb10-051-japanese-temple-singing-bowl.mp3`,
    category: "tones-resonance",
    lane: "Tones / Resonance",
    playable: true,
    containsVoice: false,
    durationSeconds: 14.544,
    clearLabelRequired: true,
    userChoiceOnly: true,
    loopEligible: false,
    tags: [
      "singing bowl",
      "bowl",
      "resonance",
      "tones",
      "tone",
      "resonant",
      "chime texture",
      "Tones / Resonance",
      "accent",
      "bowl_texture",
      "opt_in_texture",
      "low_volume_layer",
      "user_choice_only",
      "not_default_fast_start",
    ],
  },
];

export const defaultMobileCatalogSound = mobileCatalogSounds[0];

export const mobileCatalogLanes = Array.from(
  new Set(mobileCatalogSounds.map((sound) => sound.lane)),
);
